namespace StravaIntegration.DTOs;

public record StravaActivity(
    long Id,
    int ResourceState,
    string Name,
    double Distance,
    int MovingTime,
    int ElapsedTime,
    double TotalElevationGain,
    string Type,
    string SportType,
    int? WorkoutType,
    DateTime StartDate,
    DateTime StartDateLocal,
    string Timezone,
    double UtcOffset,
    string? LocationCity,
    string? LocationState,
    string? LocationCountry,
    int AchievementCount,
    int KudosCount,
    int CommentCount,
    int AthleteCount,
    int PhotoCount,
    StravaMap Map,
    bool Trainer,
    bool Commute,
    bool Manual,
    bool Private,
    string Visibility,
    bool Flagged,
    string? GearId,
    double[]? StartLatlng,
    double[]? EndLatlng,
    double? AverageSpeed,
    double? MaxSpeed,
    double? AverageCadence,
    bool HasHeartrate,
    bool HeartrateOptOut,
    bool DisplayHideHeartrateOption,
    double? ElevHigh,
    double? ElevLow,
    long UploadId,
    string UploadIdStr,
    string? ExternalId,
    bool FromAcceptedTag,
    int PrCount,
    int TotalPhotoCount,
    bool HasKudoed,
    StravaAthlete Athlete
);

public record StravaMap(
    string Id,
    string? SummaryPolyline,
    int ResourceState
);

public record Activity(
    string Name,
    double Distance,
    int MovingTime,
    int ElapsedTime,
    double TotalElevationGain,
    string Type,
    string SportType,
    double? AverageSpeed,
    double? MaxSpeed,
    double? AverageCadence,
    bool HasHeartrate,
    bool HeartrateOptOut,
    double? ElevHigh,
    double? ElevLow,
    DateTime StartDateLocal
);